[project]
name = "bookstore"
version = "0.1.0"
description = "Bookstore API"

authors = [
    {name = "Enge-Olate",email = "marcioalexisolate@live.com"}
]
requires-python = ">=3.12,<4.0"
dependencies = [
    "black (>=26.5.1,<27.0.0)",
    "factory-boy (>=3.3.3,<4.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "django (>=6.1,<7.0)",
    "djangorestframework (>=3.18.0,<4.0.0)"
]


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "bookstore.settings"
python_files = ["test*_.py", "*_test.py", "test.py"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest-django (>=4.14.0,<5.0.0)"
]
