# Generated by Django 6.1 on 2026-09-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_options_remove_order_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
