# Generated by Django 6.1 on 2026-09-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_quantity_delete_orderitem"),
        ("product", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(to="product.product"),
        ),
    ]
