# Generated by Django 6.1 on 2026-09-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product",
            new_name="products",
        ),
    ]
